spring:
  application:
    name: my-kotlin-project
feign:
  httpclient:
    disable-ssl-validation: true
server:
  port: 8090
  ssl:
    enabled: true
    key-store: src/main/resources/ssl/keys/security.p12
    key-store-type: PKCS12
    key-alias: security
    key-store-password: security